# Generated by Django 3.2.4 on 2021-06-11 03:27

from django.db import migrations


def create_department(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Department = apps.get_model("api", "Department")
    db_alias = schema_editor.connection.alias
    Department.objects.using(db_alias).bulk_create([
        Department(name="Computer Science and Engineering", code="CSE"),
        Department(name="Mechanical Engineering", code="MECH"),
        Department(name="Civil Engineering", code="CIV"),
        Department(name="Electronics and Electrical Engineering", code="EEE"),
        Department(name="Electronics and Communications Engineering", code="ECE"),
        Department(name="Information Technology", code="IT"),
    ])


def create_Tag(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Tag = apps.get_model("api", "Tag")
    db_alias = schema_editor.connection.alias
    Tag.objects.using(db_alias).bulk_create([
        Tag(slug='general',
            description='Questions which do not fall under any other category'),
        Tag(slug='ece', description='Questions related to ECE'),
        Tag(slug='cse', description='Questions related to CSE'),
        Tag(slug='eee', description='Questions related to EEE'),
        Tag(slug='civ', description='Questions related to CIV'),
        Tag(slug='mech', description='Questions related to MECH'),
        Tag(slug='math', description='Questions related to MATH'),
        Tag(slug='programming',
            description='Questions related to programming doubts or help/resources'),
        Tag(slug='placements', description='Questions related to placements'),
        Tag(slug='seeking-advice',
            description='Questions seeking advice from seniors/Alumni'),
        Tag(slug='help',
            description='Questions seeking help in a specific problem'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_department),
        migrations.RunPython(create_Tag),
    ]
