# Generated by Django 3.2.4 on 2021-06-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210611_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionflag',
            name='reason',
            field=models.CharField(choices=[('nsfw', 'Adult/Violent Content (Not Safe For Work)'), ('prom', 'Paid Promotion'), ('hurt', 'Hurting Sentiments'), ('less', 'Useless or not helpful')], max_length=50),
        ),
    ]
